### ISSUE TITLE
App APIs using multiple accessToken passports

### ISSUE THREAD

**Issue by corbanb** [jaredhanson/passport-http-bearer#37]
I think I have an odd edge case here. We are working on an iOS app using the http-bearer authentication method + trying to link [facebook-token](https://github.com/drudge/passport-facebook-token) passports together.

When we make a request we would like to pass the bearer auth token to prove a user is logged in and then attach and approve a facebook-token strategy. 

I noticed this library [sends a 400](https://github.com/jaredhanson/passport-http-bearer/blob/master/lib/strategy.js#L103) if you have a header token + an access_token on the body of a post.

Is this a security issue of not allowing both since 2 potential tokens could be sent? Whats the work around if any?

**Comment by hspinks** [comment]
@corbanb were you ever able to figure out a solution / workaround? or are there any plans to change the behavior here?

**Comment by corbanb** [comment]
I just passed in different var names and trapped them before they got to the middleware to mange it on the way these expect them in steps @hspinks.

**Comment by themikenicholson** [comment]
@corbanb V2.0 should be much more flexible with the way it handles parsing the token.  Essentially it allows you to pass in your own function that is expected to accept the request and return the JWT string.  

There was no intentional prevention of two different tokens. Chances are one of your tokens was in a default field that this strategy examined and when it didn't find the expected JWT and found your HTTP bearer token it threw the error. 

This is the other thing I didn't like about the v1.* behavior of the strategy, it checked a lot of places (HTTP authorization header, etc) in addition to whatever option the user specified.  

Let me know if there is any further action required on this issue.
